[package]
name = "slice"
version = "0.1.0"
authors = ["dahyeon-j <snoopy809622@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
